import logging
from collections import defaultdict

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.automation_log import AutomationLog
from app.models.product import Product
from app.models.purchase_order import POLine, POStatus, PurchaseOrder
from app.models.tenant import Tenant
from app.models.user import User

log = logging.getLogger(__name__)

JOB_NAME = "low_stock_agent"


async def run(db: AsyncSession) -> None:
    """For every tenant: find low-stock products, group by preferred supplier,
    create one Draft PO per supplier, and log the outcome."""
    tenants = (await db.execute(select(Tenant))).scalars().all()
    for t in tenants:
        try:
            await _run_for_tenant(db, t.id)
        except Exception as e:
            log.exception("low_stock_agent failed for tenant %s", t.id)
            db.add(AutomationLog(tenant_id=t.id, job_name=JOB_NAME, status="error", outcome={"error": str(e)}))
            await db.commit()


async def _run_for_tenant(db: AsyncSession, tenant_id: int) -> None:
    sys_user = (await db.execute(
        select(User).where(User.tenant_id == tenant_id, User.role == "admin").order_by(User.id).limit(1)
    )).scalar_one_or_none()
    if not sys_user:
        return

    products = (await db.execute(
        select(Product).where(Product.tenant_id == tenant_id, Product.is_active.is_(True))
    )).scalars().all()
    by_supplier: dict[int, list[Product]] = defaultdict(list)
    for p in products:
        if p.stock < p.reorder_threshold and p.preferred_supplier_id:
            by_supplier[p.preferred_supplier_id].append(p)

    created = []
    for supplier_id, items in by_supplier.items():
        po = PurchaseOrder(
            tenant_id=tenant_id,
            supplier_id=supplier_id,
            status=POStatus.DRAFT.value,
            notes="Auto-generated by low_stock_agent",
            created_by=sys_user.id,
            total=0,
        )
        db.add(po)
        await db.flush()
        total = 0.0
        for p in items:
            qty = max(p.reorder_threshold * 2 - p.stock, 1)
            db.add(POLine(po_id=po.id, product_id=p.id, qty=qty, unit_price=float(p.unit_price)))
            total += qty * float(p.unit_price)
        po.total = total
        created.append({"po_id": po.id, "supplier_id": supplier_id, "items": len(items), "total": total})

    db.add(AutomationLog(
        tenant_id=tenant_id, job_name=JOB_NAME, status="success",
        outcome={"draft_pos_created": created, "low_stock_count": sum(len(v) for v in by_supplier.values())},
    ))
    await db.commit()
